package cl.poo.Jframe;

import cl.poo.Clases.Empleado;
import cl.poo.Conexion.EmpleadoDAO;
import cl.poo.Validadores.ValidadorDv;
import cl.poo.Validadores.ValidadorLargo;
import cl.poo.Validadores.ValidadorRut;
import cl.poo.Validadores.ValidadorTelefono;
import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author fcoja
 */
public class FormularioeEmpleado extends javax.swing.JFrame {
    
    private Empleado empleado;
    /**
     * Creates new form FormularioeEmpleado
     */
    public FormularioeEmpleado() {
        initComponents();
        this.getContentPane().setBackground(Color.CYAN);
        empleado = new Empleado();
        Crear();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblRut = new javax.swing.JLabel();
        cmbSeleccion = new javax.swing.JComboBox<>();
        lblNombre = new javax.swing.JLabel();
        lblTelefono = new javax.swing.JLabel();
        lblApellido1 = new javax.swing.JLabel();
        lblApellido2 = new javax.swing.JLabel();
        txtTelefono = new javax.swing.JTextField();
        txtRut = new javax.swing.JTextField();
        txtDv = new javax.swing.JTextField();
        txtApellido1 = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        txtApellido2 = new javax.swing.JTextField();
        lblEmpleado = new javax.swing.JLabel();
        lblTipoEmpleado = new javax.swing.JLabel();
        btnBorrar = new javax.swing.JButton();
        btnActualizar = new javax.swing.JButton();
        lblValidadorRut = new javax.swing.JLabel();
        lblValidadorNombre = new javax.swing.JLabel();
        lblValidadorApellido1 = new javax.swing.JLabel();
        lblValidadorApellido2 = new javax.swing.JLabel();
        lblValidadorTelefono = new javax.swing.JLabel();
        lblValidadorDv = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        cmbTipoEmpleado1 = new javax.swing.JComboBox<>();
        btnBuscar = new javax.swing.JButton();
        btnListar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        btnGuardar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblRut.setFont(new java.awt.Font("Dialog", 1, 26)); // NOI18N
        lblRut.setText("RUT: ");

        cmbSeleccion.setFont(new java.awt.Font("Dialog", 1, 26)); // NOI18N
        cmbSeleccion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "CREAR EMPLEADO", "EDITAR EMPLEADO", "ELIMINAR EMPLEADO" }));
        cmbSeleccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbSeleccionActionPerformed(evt);
            }
        });

        lblNombre.setFont(new java.awt.Font("Dialog", 1, 26)); // NOI18N
        lblNombre.setText("NOMBRE: ");

        lblTelefono.setFont(new java.awt.Font("Dialog", 1, 26)); // NOI18N
        lblTelefono.setText("TELEFONO: ");

        lblApellido1.setFont(new java.awt.Font("Dialog", 1, 26)); // NOI18N
        lblApellido1.setText("APELLIDO PATERNO: ");

        lblApellido2.setFont(new java.awt.Font("Dialog", 1, 26)); // NOI18N
        lblApellido2.setText("APELLIDO MATERNO: ");

        txtTelefono.setFont(new java.awt.Font("Dialog", 0, 26)); // NOI18N

        txtRut.setFont(new java.awt.Font("Dialog", 0, 26)); // NOI18N

        txtDv.setFont(new java.awt.Font("Dialog", 0, 26)); // NOI18N

        txtApellido1.setFont(new java.awt.Font("Dialog", 0, 26)); // NOI18N
        txtApellido1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtApellido1ActionPerformed(evt);
            }
        });

        txtNombre.setFont(new java.awt.Font("Dialog", 0, 26)); // NOI18N

        txtApellido2.setFont(new java.awt.Font("Dialog", 0, 26)); // NOI18N

        lblEmpleado.setFont(new java.awt.Font("Dialog", 1, 30)); // NOI18N
        lblEmpleado.setText("EMPLEADOS SYSTEM");

        lblTipoEmpleado.setFont(new java.awt.Font("Dialog", 1, 26)); // NOI18N
        lblTipoEmpleado.setText("CARGO EMPLEADO: ");

        btnBorrar.setFont(new java.awt.Font("Dialog", 1, 26)); // NOI18N
        btnBorrar.setText("BORRAR");
        btnBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarActionPerformed(evt);
            }
        });

        btnActualizar.setFont(new java.awt.Font("Dialog", 1, 26)); // NOI18N
        btnActualizar.setText("ACTUALIZAR");
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });

        lblValidadorRut.setBackground(new java.awt.Color(255, 0, 0));
        lblValidadorRut.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        lblValidadorRut.setForeground(new java.awt.Color(255, 0, 0));

        lblValidadorNombre.setBackground(new java.awt.Color(255, 0, 0));
        lblValidadorNombre.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        lblValidadorNombre.setForeground(new java.awt.Color(255, 0, 0));

        lblValidadorApellido1.setBackground(new java.awt.Color(255, 0, 0));
        lblValidadorApellido1.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        lblValidadorApellido1.setForeground(new java.awt.Color(255, 0, 0));

        lblValidadorApellido2.setBackground(new java.awt.Color(255, 0, 0));
        lblValidadorApellido2.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        lblValidadorApellido2.setForeground(new java.awt.Color(255, 0, 0));

        lblValidadorTelefono.setBackground(new java.awt.Color(255, 0, 0));
        lblValidadorTelefono.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        lblValidadorTelefono.setForeground(new java.awt.Color(255, 0, 0));

        lblValidadorDv.setBackground(new java.awt.Color(255, 0, 0));
        lblValidadorDv.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        lblValidadorDv.setForeground(new java.awt.Color(255, 0, 0));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cl/poo/Jframe/LOGO.png"))); // NOI18N

        cmbTipoEmpleado1.setFont(new java.awt.Font("Dialog", 1, 26)); // NOI18N
        cmbTipoEmpleado1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Jefe TI", "Programador@", "Cajer@", "Supervisor@" }));
        cmbTipoEmpleado1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbTipoEmpleado1ActionPerformed(evt);
            }
        });

        btnBuscar.setFont(new java.awt.Font("Dialog", 1, 26)); // NOI18N
        btnBuscar.setText("BUSCAR");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        btnListar.setFont(new java.awt.Font("Dialog", 1, 26)); // NOI18N
        btnListar.setText("LISTAR");
        btnListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListarActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 26)); // NOI18N
        jLabel2.setText("-");

        btnGuardar.setFont(new java.awt.Font("Dialog", 1, 26)); // NOI18N
        btnGuardar.setText("GUARDAR");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtRut, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtDv, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addContainerGap()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(lblTelefono)
                                                .addComponent(lblApellido1)
                                                .addComponent(lblRut))
                                            .addComponent(lblTipoEmpleado, javax.swing.GroupLayout.Alignment.TRAILING))
                                        .addGap(18, 18, 18))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(57, 57, 57)
                                        .addComponent(lblValidadorApellido1, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(16, 16, 16)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtApellido1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cmbTipoEmpleado1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(57, 57, 57)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblValidadorTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 576, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblValidadorRut, javax.swing.GroupLayout.PREFERRED_SIZE, 425, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(lblValidadorDv, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btnGuardar)
                                .addGap(45, 45, 45)
                                .addComponent(btnActualizar)))
                        .addGap(0, 19, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 226, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblValidadorApellido2, javax.swing.GroupLayout.PREFERRED_SIZE, 599, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblValidadorNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 412, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(184, 184, 184))))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGap(62, 62, 62)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(lblApellido2)
                                                .addGap(43, 43, 43)
                                                .addComponent(txtApellido2, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(lblNombre)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGap(29, 29, 29)
                                        .addComponent(btnListar)
                                        .addGap(48, 48, 48)
                                        .addComponent(btnBorrar)))
                                .addGap(0, 126, Short.MAX_VALUE)))
                        .addGap(41, 41, 41))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(201, 201, 201))))
            .addGroup(layout.createSequentialGroup()
                .addGap(388, 388, 388)
                .addComponent(lblEmpleado)
                .addGap(97, 97, 97)
                .addComponent(cmbSeleccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEmpleado)
                    .addComponent(cmbSeleccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(8, 8, 8))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblRut)
                        .addComponent(txtRut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtDv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblNombre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblValidadorRut, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
                    .addComponent(lblValidadorNombre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblValidadorDv, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtApellido1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblApellido2)
                    .addComponent(txtApellido2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblApellido1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblValidadorApellido1, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblValidadorApellido2, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblTelefono)
                            .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblValidadorTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblTipoEmpleado)
                            .addComponent(cmbTipoEmpleado1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnActualizar)
                    .addComponent(btnListar)
                    .addComponent(btnBorrar)
                    .addComponent(btnGuardar))
                .addGap(25, 25, 25))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        
        boolean isRutValido = ValidadorRut.validarRut(txtRut.getText());
        
        
        
        if(isRutValido){
            
            empleado.setRut(txtRut.getText());
            lblValidadorRut.setText("");   
        }else{
            lblValidadorRut.setText("ERROR DEBE INGRESAR NUMERICO ENTRE 7 Y 8");
        }
        
        boolean isDvValido = ValidadorDv.validarDV(txtDv.getText());
        
        if(isDvValido) {
            empleado.setDv(txtDv.getText());
            lblValidadorDv.setText("");
        }else{
            lblValidadorDv.setText("ERROR DV");
        }
        
        boolean isNombreValido = false;
        
        try{
            ValidadorLargo.validarLargoTexto(txtNombre.getText(), 1, 60, "NOMBRES");
            empleado.setNombres(txtNombre.getText());
            lblValidadorNombre.setText("");
            isNombreValido = true;
        }catch(Exception ex){
            lblValidadorNombre.setText("ERROR...CAMPO OBLIGATORIO");
            lblValidadorNombre.setToolTipText(ex.getMessage());
        }
        
        boolean isApellidoPaternoValido = false;
        
        try{
            ValidadorLargo.validarLargoTexto(txtApellido1.getText(), 1, 60, "APELLIDO PATERNO");
            empleado.setApellidoPaterno(txtApellido1.getText());
            lblValidadorApellido1.setText("");
            isApellidoPaternoValido = true;
        }catch(Exception ex) {
            lblValidadorApellido1.setText("ERROR...CAMPO OBLIGATORIO");
            lblValidadorApellido1.setToolTipText(ex.getMessage());
        }
        
        boolean isApellidoMaternoValido = false;
        
        try{
            ValidadorLargo.validarLargoTexto(txtApellido2.getText(), 1, 60, "APELLIDO MATERNO");
            empleado.setApellidoMaterno(txtApellido2.getText());
            lblValidadorApellido2.setText("");
            isApellidoMaternoValido = true;
        }catch(Exception ex) {
            lblValidadorApellido2.setText("ERROR...CAMPO OBLIGATORIO");
            lblValidadorApellido2.setToolTipText(ex.getMessage());
        }
        
        boolean isTelefonoValido = false;
        
        try{
            ValidadorTelefono.validarInt(Integer.valueOf(txtTelefono.getText()),"TELEFONO");
            empleado.setTelefono(Integer.valueOf(txtTelefono.getText()));
            lblValidadorTelefono.setText("");
            isTelefonoValido = true;//FALTABA
        }catch(Exception ex){
            
            lblValidadorTelefono.setText("DEBE INGRESAR NUMERO DE 9 DIGITOS");
            lblValidadorTelefono.setToolTipText(ex.getMessage());
        }
        
        empleado.getTipoEmpleado().setNombreTipoEmpleado(cmbTipoEmpleado1.getSelectedItem().toString());///ES cmbTipoEmpleado1
        empleado.getTipoEmpleado().setCodigo(cmbTipoEmpleado1.getSelectedIndex()+1);
        
        if(isRutValido && isDvValido && isNombreValido && isApellidoPaternoValido && isApellidoMaternoValido && isTelefonoValido){
            empleado.imprimir();
        
        
        EmpleadoDAO dao = new EmpleadoDAO();
        boolean resultado = dao.insertar(empleado);
        
        System.out.println("insertado  ==>" + resultado);
        
        if(resultado){
            
            JOptionPane.showMessageDialog(rootPane, "USUARIO INGRESADO CORRECTAMENTE");
            limpiar();
            Crear();
        }else{
            JOptionPane.showMessageDialog(rootPane, "EL USUARIO NO SE HA PODIDO REGISTRAR");
        }
    }
        
        
        
        
        
        
        
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        boolean isNombreValido = false;
        
        empleado.setRut(txtRut.getText());
        empleado.setDv(txtDv.getText());
        
        try{
            ValidadorLargo.validarLargoTexto(txtNombre.getText(), 1, 60, "NOMBRES");
            empleado.setNombres(txtNombre.getText());
            lblValidadorNombre.setText("");
            isNombreValido = true;
        }catch(Exception ex){
            lblValidadorNombre.setText("ERROR...CAMPO OBLIGATORIO");
            lblValidadorNombre.setToolTipText(ex.getMessage());
        }
        
        boolean isApellidoPaternoValido = false;
        
        try{
            ValidadorLargo.validarLargoTexto(txtApellido1.getText(), 1, 60, "APELLIDO PATERNO");
            empleado.setApellidoPaterno(txtApellido1.getText());
            lblValidadorApellido1.setText("");
            isApellidoPaternoValido = true;
        }catch(Exception ex) {
            lblValidadorApellido1.setText("ERROR...CAMPO OBLIGATORIO");
            lblValidadorApellido1.setToolTipText(ex.getMessage());
        }
        
        boolean isApellidoMaternoValido = false;
        
        try{
            ValidadorLargo.validarLargoTexto(txtApellido2.getText(), 1, 60, "APELLIDO MATERNO");
            empleado.setApellidoMaterno(txtApellido2.getText());
            lblValidadorApellido2.setText("");
            isApellidoMaternoValido = true;
        }catch(Exception ex) {
            lblValidadorApellido2.setText("ERROR...CAMPO OBLIGATORIO");
            lblValidadorApellido2.setToolTipText(ex.getMessage());
        }
        
        boolean isTelefonoValido = false;
        
        try{
            ValidadorTelefono.validarInt(Integer.valueOf(txtTelefono.getText()),"TELEFONO");
            empleado.setTelefono(Integer.valueOf(txtTelefono.getText()));
            lblValidadorTelefono.setText("");
            isTelefonoValido = true;
        }catch(Exception ex){
            lblValidadorTelefono.setText("DEBE INGRESAR NUMERO DE 9 DIGITOS");
            lblValidadorTelefono.setToolTipText(ex.getMessage());
        }
        
        empleado.getTipoEmpleado().setNombreTipoEmpleado(cmbTipoEmpleado1.getSelectedItem().toString());
        empleado.getTipoEmpleado().setCodigo(cmbTipoEmpleado1.getSelectedIndex()+1);
        
        if(isNombreValido && isApellidoPaternoValido && isApellidoMaternoValido && isTelefonoValido){
            empleado.imprimir();
        
        
        EmpleadoDAO dao = new EmpleadoDAO();
        boolean resultado = dao.actualizar(empleado);
        
        System.out.println("actualizar  ==>" + resultado);
        
        if(resultado){
            
            JOptionPane.showMessageDialog(rootPane, "EL USUARIO DE ACTUALIZO DE FORMA CORRECTA");
            limpiar();
            Editar();  
            
        }else{
            JOptionPane.showMessageDialog(rootPane, "ERROR AL ACTUALIZAR");
        }
        }   
    }//GEN-LAST:event_btnActualizarActionPerformed

    private void btnListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarActionPerformed
        ListaEmpleado fm = new ListaEmpleado();
        fm.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnListarActionPerformed

    private void btnBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarActionPerformed
        
        
        boolean isRutValido = ValidadorRut.validarRut(txtRut.getText());
        
        if(isRutValido){
            
            empleado.setRut(txtRut.getText());
            lblValidadorRut.setText("");   
        }else{
            lblValidadorRut.setText("ERROR RUT 'XXXXXXXX'");
        }
        
        boolean isDvValido = ValidadorDv.validarDV(txtDv.getText());
        
        if(isDvValido) {
            empleado.setDv(txtDv.getText());
            lblValidadorDv.setText("");
        }else{
            lblValidadorDv.setText("ERROR DV 'X'");
        }
        
        
        String rut = txtRut.getText();
        
        String dv = txtDv.getText();

        EmpleadoDAO dao = new EmpleadoDAO();
        boolean resultado = dao.borrar(rut,dv);
        
        System.out.println("BORRAR ====> " + resultado);
        
        if(resultado && isRutValido && isDvValido){
            
            JOptionPane.showMessageDialog(rootPane, "USUARIO ELIMINADO CON EXITO");            
            limpiar();
        }else{
            JOptionPane.showMessageDialog(rootPane, "NO SE HA PODIDO ELIMINAR EL USUARIO");                        
        } 
        
            
            
        
    }//GEN-LAST:event_btnBorrarActionPerformed

    private void cmbSeleccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbSeleccionActionPerformed
        if("CREAR EMPLEADO".equals(cmbSeleccion.getSelectedItem())){           
            limpiar();
            Crear();
            lblValidadorRut.setText("");
            lblValidadorDv.setText("");
            lblValidadorNombre.setText("");
            lblValidadorApellido1.setText("");
            lblValidadorApellido2.setText("");
            lblValidadorTelefono.setText("");
        }
        if("EDITAR EMPLEADO".equals(cmbSeleccion.getSelectedItem())){       
            limpiar();
            Editar();
            lblValidadorRut.setText("");
            lblValidadorDv.setText("");
            lblValidadorNombre.setText("");
            lblValidadorApellido1.setText("");
            lblValidadorApellido2.setText("");
            lblValidadorTelefono.setText("");
            
        }
        if("ELIMINAR EMPLEADO".equals(cmbSeleccion.getSelectedItem())){
            limpiar();
            Eliminar();            
        }
    }//GEN-LAST:event_cmbSeleccionActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        
        String rut = txtRut.getText();
        String dv = txtDv.getText();
        //Data Access Object
        EmpleadoDAO dao = new EmpleadoDAO();
        Empleado emp = dao.buscarPorRut(rut, dv);
        
        if(emp != null){
            accionBuscar();
            txtNombre.setText(emp.getNombres());
            txtApellido1.setText(emp.getApellidoPaterno());
            txtApellido2.setText(emp.getApellidoMaterno());
            txtTelefono.setText(String.valueOf(emp.getTelefono()));
            emp.getTipoEmpleado().setNombreTipoEmpleado(cmbTipoEmpleado1.getSelectedItem().toString());
            emp.getTipoEmpleado().setCodigo(cmbTipoEmpleado1.getSelectedIndex()+1);

        }else{
            JOptionPane.showMessageDialog(rootPane, "El usuario no se encuentra registrado");
        } 
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void cmbTipoEmpleado1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbTipoEmpleado1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbTipoEmpleado1ActionPerformed

    private void txtApellido1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtApellido1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtApellido1ActionPerformed
    public void limpiar(){
    
        txtRut.setText("");
        txtDv.setText("");
        txtNombre.setText("");
        txtApellido1.setText("");
        txtApellido2.setText("");
        txtTelefono.setText("");
        
    }
    
    public void Editar(){
        //Habilitar campo
        txtRut.setEnabled(true);
        txtDv.setEnabled(true);
        //Ocultando lable
        lblNombre.setVisible(false);
        lblApellido1.setVisible(false);
        lblApellido2.setVisible(false);
        lblTelefono.setVisible(false);
        lblTipoEmpleado.setVisible(false);
        //VALIDADOTRES
        lblValidadorRut.setVisible(false);
        lblValidadorNombre.setVisible(true);
        lblValidadorApellido1.setVisible(true);
        lblValidadorApellido2.setVisible(true);
        lblValidadorTelefono.setVisible(true);
        lblValidadorDv.setVisible(false);
                
        
        //Ocultando textbox
        txtNombre.setVisible(false);
        txtApellido1.setVisible(false);
        txtApellido2.setVisible(false);
        txtTelefono.setVisible(false);
        cmbSeleccion.setVisible(true);
        
        btnListar.setVisible(true);
        btnActualizar.setVisible(false);
        btnGuardar.setVisible(false);
        btnBorrar.setVisible(false);  
        cmbTipoEmpleado1.setVisible(false);
        btnBuscar.setVisible(true);
    }
    
    public void accionBuscar(){
        //Deshabilitar campo
        txtRut.setEnabled(false);
        txtDv.setEnabled(false);
        
        lblNombre.setVisible(true);
        lblApellido1.setVisible(true);
        lblApellido2.setVisible(true);
        lblTelefono.setVisible(true);
        lblTipoEmpleado.setVisible(true);
        //VALIDADOTRES
        lblValidadorRut.setVisible(false);
        lblValidadorNombre.setVisible(true);
        lblValidadorApellido1.setVisible(true);
        lblValidadorApellido2.setVisible(true);
        lblValidadorTelefono.setVisible(true);
        lblValidadorDv.setVisible(false);
    
        
        txtNombre.setVisible(true);
        txtApellido1.setVisible(true);
        txtApellido2.setVisible(true);
        txtTelefono.setVisible(true);
        cmbSeleccion.setVisible(true);
        btnListar.setVisible(true);
        btnActualizar.setVisible(true);
        btnGuardar.setVisible(false);
        btnBorrar.setVisible(false);  
        cmbTipoEmpleado1.setVisible(true);
        btnBuscar.setVisible(false);

    }   
    public void Crear(){
        //Habilitar campo
        txtRut.setEnabled(true);
        txtDv.setEnabled(true);
        //Ocultando lable
        lblNombre.setVisible(true);
        lblApellido1.setVisible(true);
        lblApellido2.setVisible(true);
        lblTelefono.setVisible(true);
        lblTipoEmpleado.setVisible(true);
        
        //Ocultando textbox
        txtNombre.setVisible(true);
        txtApellido1.setVisible(true);
        txtApellido2.setVisible(true);
        txtTelefono.setVisible(true);
        cmbSeleccion.setVisible(true);
        
        btnListar.setVisible(true);
        btnActualizar.setVisible(false);
        btnGuardar.setVisible(true);
        
        btnBorrar.setVisible(false);  
        cmbTipoEmpleado1.setVisible(true);
        btnBuscar.setVisible(false);
        lblValidadorRut.setVisible(true);
        lblValidadorNombre.setVisible(true);
        lblValidadorApellido1.setVisible(true);
        lblValidadorApellido2.setVisible(true);
        lblValidadorTelefono.setVisible(true);
        lblValidadorDv.setVisible(true);
    }
    
    public void Eliminar(){
        //Habilitar campo
        txtRut.setEnabled(true); 
        txtDv.setEnabled(true);
        //Ocultando lable
        lblNombre.setVisible(false);
        lblApellido1.setVisible(false);
        lblApellido2.setVisible(false);
        lblTelefono.setVisible(false);
        lblTelefono.setVisible(false);
        lblTipoEmpleado.setVisible(false);
        //Ocultando textbox
        txtNombre.setVisible(false);
        txtApellido1.setVisible(false);
        txtApellido2.setVisible(false);
        txtTelefono.setVisible(false);
        cmbSeleccion.setVisible(true);
        
        btnActualizar.setVisible(false);
        btnListar.setVisible(true);
        btnGuardar.setVisible(false);
        btnBorrar.setVisible(true); 
        cmbTipoEmpleado1.setVisible(false);
        btnBuscar.setVisible(false);
        //VALIDADOTRES
        lblValidadorRut.setVisible(false);
        lblValidadorNombre.setVisible(false);
        lblValidadorApellido1.setVisible(false);
        lblValidadorApellido2.setVisible(false);
        lblValidadorTelefono.setVisible(false);
        lblValidadorDv.setVisible(false);
    }
      
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormularioeEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormularioeEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormularioeEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormularioeEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormularioeEmpleado().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnBorrar;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnListar;
    private javax.swing.JComboBox<String> cmbSeleccion;
    private javax.swing.JComboBox<String> cmbTipoEmpleado1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblApellido1;
    private javax.swing.JLabel lblApellido2;
    private javax.swing.JLabel lblEmpleado;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblRut;
    private javax.swing.JLabel lblTelefono;
    private javax.swing.JLabel lblTipoEmpleado;
    private javax.swing.JLabel lblValidadorApellido1;
    private javax.swing.JLabel lblValidadorApellido2;
    private javax.swing.JLabel lblValidadorDv;
    private javax.swing.JLabel lblValidadorNombre;
    private javax.swing.JLabel lblValidadorRut;
    private javax.swing.JLabel lblValidadorTelefono;
    private javax.swing.JTextField txtApellido1;
    private javax.swing.JTextField txtApellido2;
    private javax.swing.JTextField txtDv;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtRut;
    private javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables
}
